// Generated by CoffeeScript 1.4.0
(function () {
    var c, canvas, ctx, height, imgData, width, x, y, _i, _j,
        __bind = function (fn, me) {
            return function () {
                return fn.apply(me, arguments);
            };
        };

    this.Color = (function () {

        function Color(r, g, b) {
            this.r = r;
            this.g = g;
            this.b = b;
            this.mul = __bind(this.mul, this);

            this.mul = __bind(this.mul, this);

            this.sub = __bind(this.sub, this);

            this.add = __bind(this.add, this);

        }

        Color.prototype.add = function (c) {
            return new Color(this.r + c.r, this.g + c.g, this.b + c.b);
        };

        Color.prototype.sub = function (c) {
            return new Color(this.r - c.r, this.g - c.g, this.b - c.b);
        };

        Color.prototype.mul = function (c) {
            return new Color(this.r * c.r, this.g * c.g, this.b * c.b);
        };

        Color.prototype.mul = function (d) {
            return new Color(this.r * d, this.g * d, this.b * d);
        };

        return Color;

    })();

    canvas = document.getElementById("mainCanvas");

    ctx = canvas.getContext("2d");

    ctx.fillStyle = "white";

    ctx.fillRect(0, 0, canvas.width, canvas.height);

    width = canvas.width;

    height = canvas.height;

    imgData = ctx.getImageData(0, 0, width, height);

    c = new Color(0, 0.5, 1);

    for(x = _i = 0; _i <= width; x = _i += 1) {
        for(y = _j = 0; _j <= height; y = _j += 1) {
            imgData.data[(x * height + y) * 4 + 0] = c.r * 255;
            imgData.data[(x * height + y) * 4 + 1] = c.g * 255;
            imgData.data[(x * height + y) * 4 + 2] = c.b * 255;
        }
    }

    ctx.putImageData(imgData, 0, 0);

}).call(this);
