// Generated by CoffeeScript 1.4.0
(function () {
    var c, canvas, ctx, height, imgData, width, x, y, _i, _j;

    canvas = document.getElementById("mainCanvas");

    ctx = canvas.getContext("2d");

    ctx.fillStyle = "white";

    ctx.fillRect(0, 0, canvas.width, canvas.height);

    width = canvas.width;

    height = canvas.height;

    imgData = ctx.getImageData(0, 0, width, height);

    c = new Color(0, 0.5, 1);

    for(x = _i = 0; _i <= width; x = _i += 1) {
        for(y = _j = 0; _j <= height; y = _j += 1) {
            imgData.data[(x * height + y) * 4 + 0] = c.r * 255;
            imgData.data[(x * height + y) * 4 + 1] = c.g * 255;
            imgData.data[(x * height + y) * 4 + 2] = c.b * 255;
        }
    }

    ctx.putImageData(imgData, 0, 0);

}).call(this);
