// Generated by CoffeeScript 1.4.0
(function() {
  var render;

  self.addEventListener('message', (function(e) {
    var args;
    args = JSON.parse(e.data);
    return self.postMessage(args);
  }), false);

  render = function(imgData, world, cam, width, height) {
    var c, tracer, x, y, _i, _j, _results;
    tracer = new Tracer(world);
    _results = [];
    for (x = _i = 0; _i <= width; x = _i += 1) {
      for (y = _j = 0; _j <= height; y = _j += 1) {
        c = tracer.colorFor(cam.rayFor(width, height, x, y));
        imgData.data[(x * height + y) * 4 + 0] = c.r * 255.0;
        imgData.data[(x * height + y) * 4 + 1] = c.g * 255.0;
        imgData.data[(x * height + y) * 4 + 2] = c.b * 255.0;
      }
      _results.push(imgData);
    }
    return _results;
  };

}).call(this);
