// Generated by CoffeeScript 1.4.0
(function () {
    var __bind = function (fn, me) {
        return function () {
            return fn.apply(me, arguments);
        };
    };

    this.epsilon = 0.0001;

    this.Color = (function () {

        function Color(r, g, b) {
            this.r = r;
            this.g = g;
            this.b = b;
            this.mulNumber = __bind(this.mulNumber, this);

            this.mulColor = __bind(this.mulColor, this);

            this.sub = __bind(this.sub, this);

            this.add = __bind(this.add, this);

        }

        Color.prototype.add = function (c) {
            return new Color(this.r + c.r, this.g + c.g, this.b + c.b);
        };

        Color.prototype.sub = function (c) {
            return new Color(this.r - c.r, this.g - c.g, this.b - c.b);
        };

        Color.prototype.mulColor = function (c) {
            return new Color(this.r * c.r, this.g * c.g, this.b * c.b);
        };

        Color.prototype.mulNumber = function (d) {
            return new Color(this.r * d, this.g * d, this.b * d);
        };

        return Color;

    })();

    this.Ray = (function () {

        function Ray(o, d) {
            this.o = o;
            this.d = d;
            this.tOf = __bind(this.tOf, this);

            this.at = __bind(this.at, this);

        }

        Ray.prototype.at = function (t) {
            return this.o.add(this.d.mul(t));
        };

        Ray.prototype.tOf = function (p) {
            return this.o.sub(p).magnitude;
        };

        return Ray;

    })();

}).call(this);
